sudo: required

git:
  depth: false

matrix:
  include:
    - os: osx
      language: csharp
      mono: none
      dotnet: 2.1.401
      env: RID=osx.10.12-x64
    - os: linux
      env: TARGET_ARCH=amd64 RID=ubuntu.16.04-x64   RELEASE=xenial  VERSION=16.04
      language: C
    - os: linux
      env: TARGET_ARCH=arm64 RID=ubuntu.16.04-arm64 RELEASE=xenial  VERSION=16.04
      language: C

install:
  - ./ci/install-$TRAVIS_OS_NAME.sh
 
before_script:
  - lsusb

script:
  - ./ci/build-$TRAVIS_OS_NAME.sh